### PR TITLE
feat: Support Inline Fragments

### LINKED ISSUE #36: Inline Fragment Support
Ran into this issue migrating a personal project that uses the GitHub API. It seems that the inline fragments (implementations) on the `GitObject` aren't getting properly exposed. I suppose I expected to see `x.$on` or `x.$as` in the example.

**edit** After digging into GitHub's schema, they rely on returning the `GitObject` interface from `repository().object()` which can then be cast to one of `Blob`, `Tree`, `Commit`, `Tag`. After digging through the GraphQL resources, this [is a feature](https://graphql.org/learn/queries/#inline-fragments) of GraphQL. If a query/mutation returns an interface, then you can request any of the polymorphic casts of that interface.

Schema: https://api.github.com/graphql (or download at https://docs.github.com/en/graphql/overview/public-schema)

```gql
# GraphQL Query
query SelectObjectContents {
  repository(name: "codedrift", owner: "jakobo") {
    object(expression: "main:src/data/manifest.yaml") {
      ... on Blob {
        id
        text
      }
    }
  }
}
```

image

Finally, given our other conventions around unions, I suppose this is how I expected the polymorphism to be exposed.

```ts
export const selectShortlinkData = query((q) => [
  q.repository({ name: "codedrift", owner: "jakobo" }, (r) => [
    r.object({ expression: "main:src/data/shortlinks.yaml" }, (o) => [
      o.id,
      o.$on("Blob", (b) => [b.text]),
    ]),
  ]),
]);
```

### PR DESCRIPTION
**Pull request by jakobo**
This is a fix #36, implementing support for Inline Fragments in GraphQL when a resolver returns an Interface instead of an object type.

### CODE REVIEW

**Comment by jakobo** [comment]
@spion Was able to get it working by following the pattern used for `$Union`. Could definitely use another set of eyes though.

**Comment by spion** [comment]
@jakobo looks good, although I would compute the reverse map separately rather than as side effects of the forward map in its loop. I'll give it a more through look when less tired :sweat_smile:

**Comment by jakobo** [comment]
> I would compute the reverse map separately rather than as side effects of the forward map

Totally makes sense. I was just looking to save a loop on really big schemas but also understand the code would be more readable w/ a second loop.

**Comment by jakobo** [comment]
Alright, the maps are split apart. Assuming `inheritanceMap` doesn't end up overly large, the second loop shouldn't be too intense. I took the largest graphql schema I could think of (github API) and it only added about 7ms on average to the generation of the typescript file.

**Comment by spion** [comment]
Looks exactly as I would write it, thanks! :grinning:

**Comment by spion** [comment]
Published in v3.2.0

**Pull request merged**
