### PR TITLE
feat: required vs optional variables

### PR DESCRIPTION
**Pull request by spion**
This PR changes the behavior of `$` to allow optional variables if the input item allows it. Another variable `$$` allows us to specify that despite the field being optional we want a non-optional variable in the query.

Addresses some of the feedback from #20

### CODE REVIEW

**Comment by ilijaNL** [comment]
Remarks on this PR:
- It should be possible to use `null`, instead of undefined
- When you want an undefined variable, you just don't specify it?
- In my opinion, you should start with strict argument (non nullable) and opt-in for a nullable argument. Also the generated doc should conform to this.

See pr #23 for other suggested points.

**Comment by spion** [comment]
> It should be possible to use null, instead of undefined

Good point, I think I'll put something like `type NullableInput<T> = T | null | undefined`

> When you want an undefined variable, you just don't specify it?

You can still specify it explicitly as `null` or `undefined` if you want. I just thought you shouldn't necessarily have to. Does that seem weird? Is there a reason to always require the variable to be present?

> In my opinion, you should start with strict argument (non nullable) and opt-in for a nullable argument. Also the generated doc should conform to this.

The beauty in that both `$` and `$$` are fully type-safe. If the graphql input type doesn't allow a null, neither will `$`. Only if the input type allows it, so will the variable. 

The previous implementation deliberately restricted the input type to never be nullable even when the API allows it. I think this was a mistake, at least as a default - the default should match the specific input type exactly. But in some cases it might be convenient to do that, which is why I added `$$`

**Comment by ilijaNL** [comment]
> You can still specify it explicitly as null or undefined if you want. I just thought you shouldn't necessarily have to. Does that seem weird? Is there a reason to always require the variable to be present?

You are correct here. I think for the nullability we should follow the graphql spec. When an variable is nullable (so no `!`), it can be omitted as variable and will fallback to null (graphql does not have undefined). In the end it means that it should be possible to specify null or not define the variable. So `T | null | undefined` is correct.

> The beauty in that both $ and $$ are fully type-safe. 
See my pr how to achieve that as well without introduction of additional variable factory function.

**Comment by spion** [comment]
FWIW, after this change you will always be able to specify a subset of the type explicitly, even without using `$$`. For example

`$<order_by.asc | order_by.desc>('myVarName')`

will restrict the valid enum values to only contain the subset of two values instead of all the other possible ones. Similarly

`$<string>('otherVar')`

would be able to restrict a `string | null | undefined` to `string` only.

The one thing that won't work is widening the type i.e. this would be invalid

`$<string | null>('aVar')`

if the input type at the variable position is not nullable.

This is another reason why I believe `$` should match the input exacty.

**Comment by ilijaNL** [comment]
> FWIW, after this change you will always be able to specify a subset of the type explicitly, even without using `$$`. For example
> 
> `$<order_by.asc | order_by.desc>('myVarName')`
> 
> will restrict the valid enum values to only contain the subset of two values instead of all the other possible ones. Similarly
> 
> `$<string>('otherVar')`
> 
> would be able to restrict a `string | null | undefined` to `string` only.
> 
> The one thing that won't work is widening the type i.e. this would be invalid
> 
> `$<string | null>('aVar')`
> 
> if the input type at the variable position is not nullable.
> 
> This is another reason why I believe `$` should match the input exacty - it will allow specifying precise restrictions (that still include null values)

You are correct however the nullability precision restriction should be runtime aswell instead of only being compile time. Why? Because then we can generate a correct  document with correctly annotated arguments, so when a input var `arg0` is not nullabile the generated doc should contain `query (arg0: String!)`. You can't achieve this generation when you don't store any metadata about the nullability of a variable. Personally I am fine with $ and with $$ but the $$ implementation should be extended in this pr

**Comment by ilijaNL** [comment]
@spion Let me know if you need some help with this feature, I am willing to contribute

**Comment by spion** [comment]
@ilijaNL I'm still thinking about the design. I think I'll need some time to play with this and see what makes sense.

**Comment by ilijaNL** [comment]
> edit: to clarify what you said about runtime checks makes sense and is doable, i'm just thinking how all of that will interplay with default values and whether further type refinements (other than just nullability) will be needed.

I dont think you can encapsulate the default value since this library produces a TypedDocumentNode which has no notion of a default value, just the InputType and output type

**Comment by jakobo** [comment]
Just hit this bug and it pretty much killed the migration of a project I was working on. Since we're still building documentation, here was all the things I looked for & APIs I tried.

`$("emailVerified", {nullable: true})` - nullable is an exception, but it also felt like we may eventually want to dictate other typing information inside of the `$`, I'm never really a fan of the options object, but it does get used a lot.

`$.nullable("emailVerified") or $("emailVerified").nullable()` - This felt more like Nexus GraphQL, which is another builder style library we use. Additionally, the second option would be closer to how this library supports `.as()` for aliasing. Making the default nullable and doing `$("emailVerified").required()` would also make sense.

Honestly, I didn't even think about a `$$` initially because of the builder pattern.

**Comment by spion** [comment]
Thanks @jakobo . I just merged the other PR by @ilijaNL  that implements this fully correctly with runtime support. I'm thinking that `$("emailVerified").required()` makes sense and would be easy to add. Will work on updating the docs too.

**Comment by spion** [comment]
Oops - looks like the builder pattern breaks type inference. It might be possible to fix that, but for now I think we can stick to `$$`

**Pull request closed without merging**
