### PR TITLE
feat: All fields

### PR DESCRIPTION
**Pull request by michaelbridge**
See #63 for explanation.

### CODE REVIEW

**Comment by eliaharris** [comment]
It's up to @spion, but this looks good to me. I could definitely see myself using this. Is there any way to write a test for this?

**Comment by spion** [comment]
Looks good to me too. I would avoid exporting the `$` classes as I've thought of them as private implementation details and not strictly part of the interface.

For testing the `useOutputType` property argument of the `verify` helper can be used to write `helper-all.good.ts` that "accesses" all of the properties and would fail (to compile) if `all` doesn't work properly.

**Comment by michaelbridge** [comment]
Thanks. Added tests and remove the undesired exports.

**Comment by spion** [comment]
Thank you!

**Pull request merged**
